{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "ase-api",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/services/ase-api",
    "resourceVersion": "18473",
    "labels": {
      "app": "ase-api"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 8090,
        "targetPort": 3000,
        "nodePort": 32656
      }
    ],
    "selector": {
      "app": "ase-api"
    },
    "clusterIP": "10.3.0.7",
    "type": "LoadBalancer",
    "sessionAffinity": "None",
    "externalTrafficPolicy": "Cluster"
  }
}